# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2025'
email: haixia-he@uiowa.edu
full_name: haixia
gh_action_docs_preview: false
gh_action_pypi: true
github_org: haixia369
license: MIT
project_description: This is the project description.
project_name: isrp-schema
project_slug: isrp_schema

